### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file

### ISSUE THREAD

**Issue by Lv-Yi** [pangliang/apk_hack#1]
你好！good tool but need update...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file

不知道如何才能更新并用于最新的android app。

**Comment by Lv-Yi** [comment]
After updating to latest apktool 2.3.1, it works again. Tried to update this git but no luck.
So fork to https://github.com/qcarduinoyun/apk_hack and update there.

**Comment by pangliang** [comment]
@qcarduinoyun   i updated it,  thank you!
